SELECT SUM(AMOUNT) FROM BILLROW
    INNER JOIN SYSTEM.BILL B on BILLROW.BILLID = B.BILLID
WHERE B.BRANCHID = 1;

SELECT SUM(SUM(AMOUNT) * PRICE) FROM BILLROW
    INNER JOIN SYSTEM.PRODUCT P on BILLROW.PRODUCTID = P.PRODUCTID
    INNER JOIN SYSTEM.BILL B on BILLROW.BILLID = B.BILLID
WHERE B.BRANCHID = 2
GROUP BY P.PRODUCTID, PRICE;